export const CONFIG = {
    INITIAL_DIFFICULTY: 1,
    DIFFICULTY_INCREASE: 1.0001,
    MAX_STARS: 800,
    ENEMY_SPAWN_INTERVAL: 2000,
    BONUS_SPAWN_INTERVAL: 20000,
    FRICTION: 0.985,
    ACCELERATION: 1.005,
    COLOR_PLAYER: 'white',
    TEST: false,
    ENEMY_GENERATION: true
}